apiVersion: v1
kind: Pod
metadata:
  name: pod-identity
  labels:
    app: identity
spec:
  containers:
  - name: api-ctr
    image: nimb3s/identity.api:develop-0.3.7
    env:
      - name: ASPNETCORE_ENVIRONMENT
        value: Development
    ports:
      - containerPort: 80
  - name: db-ctr
    image: nimb3s/identity.database:develop-0.3.7
    env:
      - name: ASPNETCORE_ENVIRONMENT
        value: Development
    ports:
      - containerPort: 1443
#kubectl cluster-info
#kubectl apply -f pod-dev.yml
#kubectl get pods --watch
#kubectl get pods -o wide
#kubectl describe pods pod-identity

#kubectl apply -f pod-dev.yml
#kubectl apply -f port-svc-identity.yml
