apiVersion: v1
kind: Pod
metadata:
  name: identity-pod
  labels:
    app: identity
spec:
  containers:
  - name: api-ctr
    image: nimb3s/identity.api:develop-0.3.3
    env:
      - name: ASPNETCORE_ENVIRONMENT
        value: Development
    ports:
      - containerPort: 80
  - name: db-ctr
    image: nimb3s/identity.database:develop-0.3.3
    env:
      - name: ASPNETCORE_ENVIRONMENT
        value: Development
    ports:
      - containerPort: 1443
