name: Master CI Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        #os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      env:
        ASPNETCORE_ENVIRONMENT : Development
      run: dotnet build --no-restore --configuration ReleaseNoDb
#    - name: Test
#      run: dotnet test --no-build --verbosity normal

    - name: Get docker tag name
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV      

    - name: Login to DockerHub Registry
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Docker - API Building tagged image
      run: docker build -f "C:\git\identity\src\Nimb3s.Identity.Api\Dockerfile" --tag nimb3s/identity.api:${{env.RELEASE_VERSION}} --force-rm --label "com.microsoft.visual-studio.project-name=Nimb3s.Identity.Api" "C:\git\identity" --progress plain --no-cache

    - name: Docker - API Pushing tagged image to dockerhub
      run: docker push nimb3s/identity.api:${{env.RELEASE_VERSION}}

    - name: Docker - API Building latest image
      run: docker build . --file Dockerfile --tag nimb3s/identity.api:latest

    - name: Docker - API Pushing latest image to dockerhub
      run: docker push nimb3s/identity.api:latest
  # publish:
    
  #   needs: build

  #   runs-on: ubuntu-latest